INSERT INTO t_sikap (id_sikap, id_guru, id_siswa, sikap, singkatan_sikap) 
VALUES 
(NULL, '9', '1', 'pp', 'perilaku'),
(NULL, '9', '1', 'ps', 'santun'),
(NULL, '9', '1', 'pd', 'disiplin'),
(NULL, '9', '1', 'pbj', 'tanggung jawab'),
(NULL, '9', '1', 'pkj', 'kejujuran'),
(NULL, '9', '1', 'ppd', 'percaya diri'),

(NULL, '9', '2', 'pp', 'perilaku'),
(NULL, '9', '2', 'ps', 'santun'),
(NULL, '9', '2', 'pd', 'disiplin'),
(NULL, '9', '2', 'pbj', 'tanggung jawab'),
(NULL, '9', '2', 'pkj', 'kejujuran'),
(NULL, '9', '2', 'ppd', 'percaya diri'),

(NULL, '9', '3', 'pp', 'perilaku'),
(NULL, '9', '3', 'ps', 'santun'),
(NULL, '9', '3', 'pd', 'disiplin'),
(NULL, '9', '3', 'pbj', 'tanggung jawab'),
(NULL, '9', '3', 'pkj', 'kejujuran'),
(NULL, '9', '3', 'ppd', 'percaya diri'),

(NULL, '9', '4', 'pp', 'perilaku'),
(NULL, '9', '4', 'ps', 'santun'),
(NULL, '9', '4', 'pd', 'disiplin'),
(NULL, '9', '4', 'pbj', 'tanggung jawab'),
(NULL, '9', '4', 'pkj', 'kejujuran'),
(NULL, '9', '4', 'ppd', 'percaya diri'),

(NULL, '9', '5', 'pp', 'perilaku'),
(NULL, '9', '5', 'ps', 'santun'),
(NULL, '9', '5', 'pd', 'disiplin'),
(NULL, '9', '5', 'pbj', 'tanggung jawab'),
(NULL, '9', '5', 'pkj', 'kejujuran'),
(NULL, '9', '5', 'ppd', 'percaya diri'),

(NULL, '9', '6', 'pp', 'perilaku'),
(NULL, '9', '6', 'ps', 'santun'),
(NULL, '9', '6', 'pd', 'disiplin'),
(NULL, '9', '6', 'pbj', 'tanggung jawab'),
(NULL, '9', '6', 'pkj', 'kejujuran'),
(NULL, '9', '6', 'ppd', 'percaya diri'),

(NULL, '9', '7', 'pp', 'perilaku'),
(NULL, '9', '7', 'ps', 'santun'),
(NULL, '9', '7', 'pd', 'disiplin'),
(NULL, '9', '7', 'pbj', 'tanggung jawab'),
(NULL, '9', '7', 'pkj', 'kejujuran'),
(NULL, '9', '7', 'ppd', 'percaya diri'),

(NULL, '9', '8', 'pp', 'perilaku'),
(NULL, '9', '8', 'ps', 'santun'),
(NULL, '9', '8', 'pd', 'disiplin'),
(NULL, '9', '8', 'pbj', 'tanggung jawab'),
(NULL, '9', '8', 'pkj', 'kejujuran'),
(NULL, '9', '8', 'ppd', 'percaya diri'),

(NULL, '9', '9', 'pp', 'perilaku'),
(NULL, '9', '9', 'ps', 'santun'),
(NULL, '9', '9', 'pd', 'disiplin'),
(NULL, '9', '9', 'pbj', 'tanggung jawab'),
(NULL, '9', '9', 'pkj', 'kejujuran'),
(NULL, '9', '9', 'ppd', 'percaya diri'),

(NULL, '9', '10', 'pp', 'perilaku'),
(NULL, '9', '10', 'ps', 'santun'),
(NULL, '9', '10', 'pd', 'disiplin'),
(NULL, '9', '10', 'pbj', 'tanggung jawab'),
(NULL, '9', '10', 'pkj', 'kejujuran'),
(NULL, '9', '10', 'ppd', 'percaya diri'),


(NULL, '9', '11', 'pp', 'perilaku'),
(NULL, '9', '11', 'ps', 'santun'),
(NULL, '9', '11', 'pd', 'disiplin'),
(NULL, '9', '11', 'pbj', 'tanggung jawab'),
(NULL, '9', '11', 'pkj', 'kejujuran'),
(NULL, '9', '11', 'ppd', 'percaya diri'),

(NULL, '9', '12', 'pp', 'perilaku'),
(NULL, '9', '12', 'ps', 'santun'),
(NULL, '9', '12', 'pd', 'disiplin'),
(NULL, '9', '12', 'pbj', 'tanggung jawab'),
(NULL, '9', '12', 'pkj', 'kejujuran'),
(NULL, '9', '12', 'ppd', 'percaya diri'),

(NULL, '9', '13', 'pp', 'perilaku'),
(NULL, '9', '13', 'ps', 'santun'),
(NULL, '9', '13', 'pd', 'disiplin'),
(NULL, '9', '13', 'pbj', 'tanggung jawab'),
(NULL, '9', '13', 'pkj', 'kejujuran'),
(NULL, '9', '13', 'ppd', 'percaya diri'),

(NULL, '9', '14', 'pp', 'perilaku'),
(NULL, '9', '14', 'ps', 'santun'),
(NULL, '9', '14', 'pd', 'disiplin'),
(NULL, '9', '14', 'pbj', 'tanggung jawab'),
(NULL, '9', '14', 'pkj', 'kejujuran'),
(NULL, '9', '14', 'ppd', 'percaya diri'),

(NULL, '9', '15', 'pp', 'perilaku'),
(NULL, '9', '15', 'ps', 'santun'),
(NULL, '9', '15', 'pd', 'disiplin'),
(NULL, '9', '15', 'pbj', 'tanggung jawab'),
(NULL, '9', '15', 'pkj', 'kejujuran'),
(NULL, '9', '15', 'ppd', 'percaya diri'),

(NULL, '9', '16', 'pp', 'perilaku'),
(NULL, '9', '16', 'ps', 'santun'),
(NULL, '9', '16', 'pd', 'disiplin'),
(NULL, '9', '16', 'pbj', 'tanggung jawab'),
(NULL, '9', '16', 'pkj', 'kejujuran'),
(NULL, '9', '16', 'ppd', 'percaya diri'),

(NULL, '9', '17', 'pp', 'perilaku'),
(NULL, '9', '17', 'ps', 'santun'),
(NULL, '9', '17', 'pd', 'disiplin'),
(NULL, '9', '17', 'pbj', 'tanggung jawab'),
(NULL, '9', '17', 'pkj', 'kejujuran'),
(NULL, '9', '17', 'ppd', 'percaya diri'),

(NULL, '9', '18', 'pp', 'perilaku'),
(NULL, '9', '18', 'ps', 'santun'),
(NULL, '9', '18', 'pd', 'disiplin'),
(NULL, '9', '18', 'pbj', 'tanggung jawab'),
(NULL, '9', '18', 'pkj', 'kejujuran'),
(NULL, '9', '18', 'ppd', 'percaya diri'),

(NULL, '9', '19', 'pp', 'perilaku'),
(NULL, '9', '19', 'ps', 'santun'),
(NULL, '9', '19', 'pd', 'disiplin'),
(NULL, '9', '19', 'pbj', 'tanggung jawab'),
(NULL, '9', '19', 'pkj', 'kejujuran'),
(NULL, '9', '19', 'ppd', 'percaya diri'),

(NULL, '9', '20', 'pp', 'perilaku'),
(NULL, '9', '20', 'ps', 'santun'),
(NULL, '9', '20', 'pd', 'disiplin'),
(NULL, '9', '20', 'pbj', 'tanggung jawab'),
(NULL, '9', '20', 'pkj', 'kejujuran'),
(NULL, '9', '20', 'ppd', 'percaya diri'),



(NULL, '9', '21', 'pp', 'perilaku'),
(NULL, '9', '21', 'ps', 'santun'),
(NULL, '9', '21', 'pd', 'disiplin'),
(NULL, '9', '21', 'pbj', 'tanggung jawab'),
(NULL, '9', '21', 'pkj', 'kejujuran'),
(NULL, '9', '21', 'ppd', 'percaya diri'),

(NULL, '9', '22', 'pp', 'perilaku'),
(NULL, '9', '22', 'ps', 'santun'),
(NULL, '9', '22', 'pd', 'disiplin'),
(NULL, '9', '22', 'pbj', 'tanggung jawab'),
(NULL, '9', '22', 'pkj', 'kejujuran'),
(NULL, '9', '22', 'ppd', 'percaya diri'),

(NULL, '9', '23', 'pp', 'perilaku'),
(NULL, '9', '23', 'ps', 'santun'),
(NULL, '9', '23', 'pd', 'disiplin'),
(NULL, '9', '23', 'pbj', 'tanggung jawab'),
(NULL, '9', '23', 'pkj', 'kejujuran'),
(NULL, '9', '23', 'ppd', 'percaya diri'),

(NULL, '9', '24', 'pp', 'perilaku'),
(NULL, '9', '24', 'ps', 'santun'),
(NULL, '9', '24', 'pd', 'disiplin'),
(NULL, '9', '24', 'pbj', 'tanggung jawab'),
(NULL, '9', '24', 'pkj', 'kejujuran'),
(NULL, '9', '24', 'ppd', 'percaya diri'),

(NULL, '9', '25', 'pp', 'perilaku'),
(NULL, '9', '25', 'ps', 'santun'),
(NULL, '9', '25', 'pd', 'disiplin'),
(NULL, '9', '25', 'pbj', 'tanggung jawab'),
(NULL, '9', '25', 'pkj', 'kejujuran'),
(NULL, '9', '25', 'ppd', 'percaya diri'),

(NULL, '9', '26', 'pp', 'perilaku'),
(NULL, '9', '26', 'ps', 'santun'),
(NULL, '9', '26', 'pd', 'disiplin'),
(NULL, '9', '26', 'pbj', 'tanggung jawab'),
(NULL, '9', '26', 'pkj', 'kejujuran'),
(NULL, '9', '26', 'ppd', 'percaya diri'),

(NULL, '9', '27', 'pp', 'perilaku'),
(NULL, '9', '27', 'ps', 'santun'),
(NULL, '9', '27', 'pd', 'disiplin'),
(NULL, '9', '27', 'pbj', 'tanggung jawab'),
(NULL, '9', '27', 'pkj', 'kejujuran'),
(NULL, '9', '27', 'ppd', 'percaya diri'),

(NULL, '9', '28', 'pp', 'perilaku'),
(NULL, '9', '28', 'ps', 'santun'),
(NULL, '9', '28', 'pd', 'disiplin'),
(NULL, '9', '28', 'pbj', 'tanggung jawab'),
(NULL, '9', '28', 'pkj', 'kejujuran'),
(NULL, '9', '28', 'ppd', 'percaya diri'),

(NULL, '9', '29', 'pp', 'perilaku'),
(NULL, '9', '29', 'ps', 'santun'),
(NULL, '9', '29', 'pd', 'disiplin'),
(NULL, '9', '29', 'pbj', 'tanggung jawab'),
(NULL, '9', '29', 'pkj', 'kejujuran'),
(NULL, '9', '29', 'ppd', 'percaya diri'),

(NULL, '9', '30', 'pp', 'perilaku'),
(NULL, '9', '30', 'ps', 'santun'),
(NULL, '9', '30', 'pd', 'disiplin'),
(NULL, '9', '30', 'pbj', 'tanggung jawab'),
(NULL, '9', '30', 'pkj', 'kejujuran'),
(NULL, '9', '30', 'ppd', 'percaya diri'),



(NULL, '9', '31', 'pp', 'perilaku'),
(NULL, '9', '31', 'ps', 'santun'),
(NULL, '9', '31', 'pd', 'disiplin'),
(NULL, '9', '31', 'pbj', 'tanggung jawab'),
(NULL, '9', '31', 'pkj', 'kejujuran'),
(NULL, '9', '31', 'ppd', 'percaya diri'),

(NULL, '9', '32', 'pp', 'perilaku'),
(NULL, '9', '32', 'ps', 'santun'),
(NULL, '9', '32', 'pd', 'disiplin'),
(NULL, '9', '32', 'pbj', 'tanggung jawab'),
(NULL, '9', '32', 'pkj', 'kejujuran'),
(NULL, '9', '32', 'ppd', 'percaya diri'),

(NULL, '9', '33', 'pp', 'perilaku'),
(NULL, '9', '33', 'ps', 'santun'),
(NULL, '9', '33', 'pd', 'disiplin'),
(NULL, '9', '33', 'pbj', 'tanggung jawab'),
(NULL, '9', '33', 'pkj', 'kejujuran'),
(NULL, '9', '33', 'ppd', 'percaya diri'),

(NULL, '9', '34', 'pp', 'perilaku'),
(NULL, '9', '34', 'ps', 'santun'),
(NULL, '9', '34', 'pd', 'disiplin'),
(NULL, '9', '34', 'pbj', 'tanggung jawab'),
(NULL, '9', '34', 'pkj', 'kejujuran'),
(NULL, '9', '34', 'ppd', 'percaya diri'),

(NULL, '9', '35', 'pp', 'perilaku'),
(NULL, '9', '35', 'ps', 'santun'),
(NULL, '9', '35', 'pd', 'disiplin'),
(NULL, '9', '35', 'pbj', 'tanggung jawab'),
(NULL, '9', '35', 'pkj', 'kejujuran'),
(NULL, '9', '35', 'ppd', 'percaya diri'),

(NULL, '9', '36', 'pp', 'perilaku'),
(NULL, '9', '36', 'ps', 'santun'),
(NULL, '9', '36', 'pd', 'disiplin'),
(NULL, '9', '36', 'pbj', 'tanggung jawab'),
(NULL, '9', '36', 'pkj', 'kejujuran'),
(NULL, '9', '36', 'ppd', 'percaya diri'),

(NULL, '9', '37', 'pp', 'perilaku'),
(NULL, '9', '37', 'ps', 'santun'),
(NULL, '9', '37', 'pd', 'disiplin'),
(NULL, '9', '37', 'pbj', 'tanggung jawab'),
(NULL, '9', '37', 'pkj', 'kejujuran'),
(NULL, '9', '37', 'ppd', 'percaya diri'),

(NULL, '9', '38', 'pp', 'perilaku'),
(NULL, '9', '38', 'ps', 'santun'),
(NULL, '9', '38', 'pd', 'disiplin'),
(NULL, '9', '38', 'pbj', 'tanggung jawab'),
(NULL, '9', '38', 'pkj', 'kejujuran'),
(NULL, '9', '38', 'ppd', 'percaya diri'),

(NULL, '9', '39', 'pp', 'perilaku'),
(NULL, '9', '39', 'ps', 'santun'),
(NULL, '9', '39', 'pd', 'disiplin'),
(NULL, '9', '39', 'pbj', 'tanggung jawab'),
(NULL, '9', '39', 'pkj', 'kejujuran'),
(NULL, '9', '39', 'ppd', 'percaya diri'),

(NULL, '9', '40', 'pp', 'perilaku'),
(NULL, '9', '40', 'ps', 'santun'),
(NULL, '9', '40', 'pd', 'disiplin'),
(NULL, '9', '40', 'pbj', 'tanggung jawab'),
(NULL, '9', '40', 'pkj', 'kejujuran'),
(NULL, '9', '40', 'ppd', 'percaya diri')


;